include: package:lints/recommended.yaml

linter:
  rules:
    constant_identifier_names : false
    always_declare_return_types : true
    camel_case_types : true
    prefer_single_quotes : true
    sort_child_properties_last : true


# analyzer:
#   exclude:
#     - path/to/excluded/files/**
